# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Future Economy Council
title-abbreviated: Future Economy Council
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Future Economy Council.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isomerpages-futureeconomy.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

is_government: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text


collections:
  about:
    output: true
  industries:
    output: true
  success-stories:
    output: true
  innovation:
    output: true
  internationalisation:
    output: true
  productivity:
    output: true
  industries:
    output: true
  industry-transformation-maps:
    output: true
  built-environment:
    output: true
  essential-and-domestic-services:
    output: true
  lifestyle:
    output: true
  retail:
    output: true
  food-services:
    output: true
  food-manufacturing:
    output: true
  trade-and-connectivity:
    output: true
  logistics:
    output: true
  manufacturing:
    output: true
  aerospace:
    output: true
  precision-engineering:
    output: true
  modern-services:
    output: true
  articles:
    output: true
  resources:
    output: true

# Resource Room and Pagination
resources_name: "media-and-news"
paginate: 12
paginate_path: "/media-and-news/page:num"

# Site configuration
####################
homepage_hero_i_want_to: false
homepage_resources: true

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
